//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Icon_spriteatlasv2
    {
        public const string BundleName = "icon_spriteatlasv2";
        public const string ICON = "Icon";
    }
    public class Sfs
    {
        public const string BundleName = "sfs";
        public const string ABILITY_LEVEL_UP = "ability_level_up";
        public const string ACHIEVEMENT = "Achievement";
        public const string BALL = "ball";
        public const string BOMB = "bomb";
        public const string BUTTONCLICK = "ButtonClick";
        public const string COIN = "coin";
        public const string DIE = "die";
        public const string ENEMY_DIE = "enemy_die";
        public const string EXP = "exp";
        public const string GAME_PASS = "game_pass";
        public const string GET_ALL_EXP = "get_all_exp";
        public const string HIT = "hit";
        public const string HP = "hp";
        public const string HURT = "hurt";
        public const string KNIFE = "knife";
        public const string LEVEL_UP = "level_up";
        public const string TREASUER_CHEST = "treasuer_chest";
        public const string PADDLE = "paddle";
    }
    public class Testuigamepanel_unity
    {
        public const string BundleName = "testuigamepanel_unity";
        public const string TESTUIGAMEPANEL = "TestUIGamePanel";
    }
    public class Uigameoverpanel_prefab
    {
        public const string BundleName = "uigameoverpanel_prefab";
        public const string UIGAMEOVERPANEL = "UIGameOverPanel";
    }
    public class Uigamepanel_prefab
    {
        public const string BundleName = "uigamepanel_prefab";
        public const string UIGAMEPANEL = "UIGamePanel";
    }
    public class Uigamepaspanel_prefab
    {
        public const string BundleName = "uigamepaspanel_prefab";
        public const string UIGAMEPASPANEL = "UIGamePasPanel";
    }
    public class Uigamestartpanel_prefab
    {
        public const string BundleName = "uigamestartpanel_prefab";
        public const string UIGAMESTARTPANEL = "UIGameStartPanel";
    }
}
